#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
#
# Copyright 2012 Andrej A Antonov <polymorphm@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

assert str is not bytes

REQUIRED_PACKAGES = (
    # yet nothing
)

import sys, os.path
for pkg in REQUIRED_PACKAGES:
    sys.path.append(os.path.abspath(os.path.join(
            os.path.dirname(__file__), 'site-packages', pkg)))

from lib_age_backup_2012_02_29.main import main

if __name__ == '__main__':
    error = main()
    
    if error is not None:
        exit(code=error)
